import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://alfaschools.gr'
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/articles/',
          '/services/',
          '/contact/',
          '/why-us/',
          '/news/',
          '/games/',
          '/legal/',
          '/tags/',
          // Enhanced language-specific routes
          '/services/english/',
          '/services/french/',
          '/services/ielts-preparation/',
          '/services/toefl-preparation/',
          '/services/cambridge-exams/',
          '/services/delf-preparation/',
          '/services/dalf-preparation/',
          // Location-specific routes
          '/locations/chalandri/',
          '/locations/nea-filadelfeia/',
          '/locations/athens/',
          // Course-specific routes
          '/courses/beginner-english/',
          '/courses/intermediate-english/',
          '/courses/advanced-english/',
          '/courses/beginner-french/',
          '/courses/intermediate-french/',
          '/courses/advanced-french/',
          '/courses/kids-english/',
          '/courses/teens-english/',
          '/courses/adults-english/',
          '/courses/kids-french/',
          '/courses/teens-french/',
          '/courses/adults-french/',
          // Exam preparation routes
          '/exams/ielts/',
          '/exams/toefl/',
          '/exams/cambridge/',
          '/exams/delf/',
          '/exams/dalf/',
          // Game-specific routes
          '/games/english/vocabulary/',
          '/games/english/grammar/',
          '/games/english/conversation/',
          '/games/english/anagrams/',
          '/games/french/vocabulary/',
          '/games/french/grammar/',
          '/games/french/conversation/',
          '/games/french/anagrams/',
          '/iframe-test/',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
          '/*.json$',
          '/*?*',
          '/editor-demo/',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/articles/',
          '/services/',
          '/contact/',
          '/why-us/',
          '/news/',
          '/games/',
          '/legal/',
          '/tags/',
          // Enhanced language-specific routes
          '/services/english/',
          '/services/french/',
          '/services/ielts-preparation/',
          '/services/toefl-preparation/',
          '/services/cambridge-exams/',
          '/services/delf-preparation/',
          '/services/dalf-preparation/',
          // Location-specific routes
          '/locations/chalandri/',
          '/locations/nea-filadelfeia/',
          '/locations/athens/',
          // Course-specific routes
          '/courses/beginner-english/',
          '/courses/intermediate-english/',
          '/courses/advanced-english/',
          '/courses/beginner-french/',
          '/courses/intermediate-french/',
          '/courses/advanced-french/',
          '/courses/kids-english/',
          '/courses/teens-english/',
          '/courses/adults-english/',
          '/courses/kids-french/',
          '/courses/teens-french/',
          '/courses/adults-french/',
          // Exam preparation routes
          '/exams/ielts/',
          '/exams/toefl/',
          '/exams/cambridge/',
          '/exams/delf/',
          '/exams/dalf/',
          // Game-specific routes
          '/games/english/vocabulary/',
          '/games/english/grammar/',
          '/games/english/conversation/',
          '/games/english/anagrams/',
          '/games/french/vocabulary/',
          '/games/french/grammar/',
          '/games/french/conversation/',
          '/games/french/anagrams/',
          '/iframe-test/',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
          '/editor-demo/',
        ],
        crawlDelay: 0,
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/articles/',
          '/services/',
          '/contact/',
          '/why-us/',
          '/news/',
          '/games/',
          '/legal/',
          '/tags/',
          // Enhanced language-specific routes
          '/services/english/',
          '/services/french/',
          '/services/ielts-preparation/',
          '/services/toefl-preparation/',
          '/services/cambridge-exams/',
          '/services/delf-preparation/',
          '/services/dalf-preparation/',
          // Location-specific routes
          '/locations/chalandri/',
          '/locations/nea-filadelfeia/',
          '/locations/athens/',
          // Course-specific routes
          '/courses/beginner-english/',
          '/courses/intermediate-english/',
          '/courses/advanced-english/',
          '/courses/beginner-french/',
          '/courses/intermediate-french/',
          '/courses/advanced-french/',
          '/courses/kids-english/',
          '/courses/teens-english/',
          '/courses/adults-english/',
          '/courses/kids-french/',
          '/courses/teens-french/',
          '/courses/adults-french/',
          // Exam preparation routes
          '/exams/ielts/',
          '/exams/toefl/',
          '/exams/cambridge/',
          '/exams/delf/',
          '/exams/dalf/',
          // Game-specific routes
          '/games/english/vocabulary/',
          '/games/english/grammar/',
          '/games/english/conversation/',
          '/games/english/anagrams/',
          '/games/french/vocabulary/',
          '/games/french/grammar/',
          '/games/french/conversation/',
          '/games/french/anagrams/',
          '/iframe-test/',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
          '/editor-demo/',
        ],
        crawlDelay: 1,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}